// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExistsFile() {
  return window['go']['main']['OperateFile']['ExistsFile']();
}

export function GetContent() {
  return window['go']['main']['OperateFile']['GetContent']();
}

export function SetContext(arg1) {
  return window['go']['main']['OperateFile']['SetContext'](arg1);
}

export function SetFilePathWithDialog() {
  return window['go']['main']['OperateFile']['SetFilePathWithDialog']();
}

export function WriteFile(arg1) {
  return window['go']['main']['OperateFile']['WriteFile'](arg1);
}
